-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE * (100-D.DISCOUNT_RATE) *30 DIV 100 AS FEE
FROM (SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, A.OPTIONS,
      B.HISTORY_ID, DATE_FORMAT(B.START_DATE,'%Y-%m-%d') AS START_DATE,
      DATE_FORMAT(B.END_DATE,'%Y-%m-%d') AS END_DATE
     FROM CAR_RENTAL_COMPANY_CAR A
     INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
     ON A.CAR_ID=B.CAR_ID) AS C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE=D.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV')
AND C.CAR_ID IN (SELECT CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   GROUP BY CAR_ID
                   HAVING MAX(START_DATE) > '2022-11-30'
                    OR MAX(END_DATE) < '2022-11-01')
AND D.DURATION_TYPE LIKE '30%'
AND C.DAILY_FEE * (100-D.DISCOUNT_RATE) DIV 100 * 30 BETWEEN 500000 AND (2000000-1)
GROUP BY C.CAR_ID
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC