-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, CONCAT(CITY,' ' ,STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체 주소',
CASE LENGTH(B.TLNO)
		WHEN 11 THEN CONCAT(LEFT(B.TLNO, 3), '-', MID(B.TLNO, 4, 4), '-', RIGHT(B.TLNO, 4))
        WHEN 10 THEN CONCAT(LEFT(B.TLNO, 3), '-', MID(B.TLNO, 4, 3), '-', RIGHT(B.TLNO, 4))
	END AS PhoneNumber
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_USER B
ON A.WRITER_ID=B.USER_ID
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
ORDER BY B.USER_ID DESC