-- 코드를 입력하세요
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, SUM(D.SALES*C.PRICE) AS TOTAL_SALES
FROM (SELECT A.BOOK_ID,A.CATEGORY,A.AUTHOR_ID,A.PRICE,A.PUBLISHED_DATE,
      B.AUTHOR_NAME
      FROM BOOK A
      INNER JOIN AUTHOR B
      ON A.AUTHOR_ID=B.AUTHOR_ID) AS C
INNER JOIN BOOK_SALES D
ON C.BOOK_ID=D.BOOK_ID
WHERE D.SALES_DATE LIKE '2022-01%'
GROUP BY C.AUTHOR_ID, C.CATEGORY
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC