SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_INFO AS C
WHERE C.ITEM_ID IN (SELECT B.ITEM_ID
                    FROM ITEM_INFO AS A
                    INNER JOIN ITEM_TREE AS B
                    ON A.ITEM_ID=B.PARENT_ITEM_ID
                    WHERE A.RARITY='RARE')
ORDER BY C.ITEM_ID DESC