-- 코드를 입력하세요
SELECT C.APNT_NO, C.PT_NAME, C.PT_NO, D.MCDP_CD, D.DR_NAME, C.APNT_YMD
FROM (SELECT A.APNT_YMD, A.APNT_NO, A.PT_NO, A.MCDP_CD, B.PT_NAME,
      A.APNT_CNCL_YN, A.MDDR_ID
     FROM APPOINTMENT A
     INNER JOIN PATIENT B
     ON A.PT_NO=B.PT_NO) AS C
INNER JOIN DOCTOR D
ON C.MDDR_ID=D.DR_ID
WHERE C.APNT_CNCL_YN ='N'
AND C.MCDP_CD ='CS'
AND C.APNT_YMD LIKE '2022-04-13%'
ORDER BY 6