-- 코드를 입력하세요
SELECT DISTINCT B.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN CAR_RENTAL_COMPANY_CAR B
ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE LIKE '세단'
AND A.START_DATE LIKE '2022-10%'
ORDER BY B.CAR_ID DESC